repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html
  - repo: https://github.com/python/black.git
    rev: 21.9b0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3
        args: ["--max-line-length", "88", "--extend-ignore", "E203"]
        # https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language_version: python3
